### PR TITLE
Switch core.xhr to XMLHttpRequest

### PR DESCRIPTION
**Pull request by dborkan**
Switch core.xhr to XMLHttpRequest.  This is a workaround for https://github.com/freedomjs/freedom/issues/301.  Tested by leaving uProxy logged in with GitHub overnight using the 1000ms message polling interval.

[Review on Reviewable](https://reviewable.io/reviews/freedomjs/freedom-social-github/10)

### CODE REVIEW

**Comment by PissOffNYC** [comment]
@dborkan this is a test comment, please ignore

**Comment by lucyhe** [comment]
just a question and potential extra line to remove, but looks good :+1: :) !

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/github-social-provider.js, line 287 [r1]](https://reviewable.io:443/reviews/freedomjs/freedom-social-github/10#-K5arkcvh2WqjTVy2DNd:-K5arkcvh2WqjTVy2DNe:-548304523) ([raw file](https://github.com/freedomjs/freedom-social-github/blob/4f23ce4acef28d30f9ef57970c29f514bc27aab4/src/github-social-provider.js#L287)):_
It doesn't look like this is ever used

---

_[src/github-social-provider.js, line 306 [r1]](https://reviewable.io:443/reviews/freedomjs/freedom-social-github/10#-K5asvyFiBkRhhaVdFxS:-K5asvyFiBkRhhaVdFxT:-535882118) ([raw file](https://github.com/freedomjs/freedom-social-github/blob/4f23ce4acef28d30f9ef57970c29f514bc27aab4/src/github-social-provider.js#L306)):_
Is this needed somewhere later?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/freedomjs/freedom-social-github/10#-:-K5asyZhoHph8odRyRv7:1850236758)_

**Comment by ryscheng** [comment]
Why not just close the core.xhr to prevent the memory leak?

**Comment by dborkan** [comment]
I can do that in a future pull request.  We need to get this launched today and it's still not clear what the best way to close XHRs is

**Comment by dborkan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/github-social-provider.js, line 287 [r1]](https://reviewable.io:443/reviews/freedomjs/freedom-social-github/10#-K5arkcvh2WqjTVy2DNd:-K5axfM0yq4cbh6FqIIm:1066114929) ([raw file](https://github.com/freedomjs/freedom-social-github/blob/4f23ce4acef28d30f9ef57970c29f514bc27aab4/src/github-social-provider.js#L287)):_
This was already here, Salome is going to clean this up in a future pull request

---

_[src/github-social-provider.js, line 306 [r1]](https://reviewable.io:443/reviews/freedomjs/freedom-social-github/10#-K5asvyFiBkRhhaVdFxS:-K5axj5_i61tb76GdfI-:280089912) ([raw file](https://github.com/freedomjs/freedom-social-github/blob/4f23ce4acef28d30f9ef57970c29f514bc27aab4/src/github-social-provider.js#L306)):_
I check with Salome, this is wanted (it was in the NPM version but not yet in GitHub)

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/freedomjs/freedom-social-github/10)_

**Pull request merged**
